### ISSUE TITLE
Feature request: Add a few basic DOM operations to XmlQueryFront

### ISSUE THREAD

**Issue by gcampbell** [unwire/handsoap#1]
In one of my Handsoap usecases, I'm retrieving a large set of DataPoint nodes, each with timestamp and value as child nodes, as follows:
    <DataPoint>
        <timestamp>2009-10-07T12:30:00</timestamp>
        <value>5</value>
    </DataPoint>

As I understand it, the only way to individually retrieve the timestamp and value nodes for each DataPoint is through XPath, which is a relatively heavyweight operation compared to simple retrieval of both child nodes for a use case like this.  Simply adding a "children()" method would probably be sufficient.

I may end up adding this in myself, of course, but just wanted to "officially" put it out as a suggestion.

**Comment by troelskn** [comment]
By heavyweight, I assume that you mean raw performance? If that is the case, did you actually measure the difference between dom traversal and xpath querying? My gut feeling is that the difference is much smaller than you might think. In the case of xmllib/nokogiri, the xpath querying happens in the external library, which is presumably quite efficient. Traversing the dom would potentially be _more_ intensive than querying. Now, I don't have any metrics, so this is just my best guess, but I would suggest that you measure it. Even if traversal _is_ faster, you would probably need very large datasets for it to matter; The time taken to parse the xml and in the http-layer will most likely dwarf it by comparison.

That said, an xpath query offers a level of abstraction, which is probably better for your application design. With traversal, you have a tendency to make assumptions about the structure of the xml, so if it changes your application may break easier.

**Comment by gcampbell** [comment]
I agree that hard numbers are useful for this sort of thing, so following is my benchmark:

```
            user     system      total        real
DOM     4.920000   0.200000   5.120000 (  6.703107)
xpath  16.030000   0.290000  16.320000 ( 18.201955)
```

This was for a dataset of two weeks of one-minute data, thus 20160 data points.  For the DOM solution, I used native_element to get at the underlying Nokogiri nodes.  My use case may be atypical, of course, and I'm not worried about cross-XML-library compatibility for this particular code, so I can understand if you'd prefer to leave this sort of thing out of the API.

**Comment by troelskn** [comment]
I must say, that was a bigger difference than I expected. Probably because you are calling xpath twice, thereby hitting the external api twice, rather than just one call to `#children`. I've added a `#children` method to the api now, so you can use it without sacrificing portability.
