### ISSUE TITLE
Ruby 1.9.1 incompatibility in http.rb

### ISSUE THREAD

**Issue by biot023** [unwire/handsoap#10]
Fixed it with this: http://gist.github.com/300910
Cheers,
   Doug.

**Comment by troelskn** [comment]
Is this issue still relevant, with the current version of Handsoap?

**Comment by jimmiw** [comment]
A fix was added some time ago (before the last big merge). This was removed again because of incompatibility with ruby 1.8.6.

**Comment by troelskn** [comment]
OK - Thought so, but wanted to make sure. I'll close the issue then.
