### ISSUE TITLE
Default namespace

### ISSUE THREAD

**Issue by ta** [unwire/handsoap#11]
Hi,

1 - As far as I can tell, handsoap only supports prefixed namespaces and not default namespaces(*) like this: "... &lt;books xmlns="http://somebooksite.com/book_spec"&gt; ...".

(*) http://www.w3.org/TR/REC-xml-names/#defaulting

Am I wrong in that observation? If not, will you consider adding this feature?

2 - Some services defines more than one namespace in the envelope:

<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

Is this possible with handsoap? If not, will you consider adding this feature?

Regards,
Tonni - who is trying to wrap his head around xml/soap

**Comment by speedmax** [comment]
I encounter a webservice which has default name space too.. 

anyone work around this issue?

**Comment by speedmax** [comment]
here is a patch that works for me

https://gist.github.com/9cc616c94f366c599df0
