### ISSUE TITLE
Curb or httpclient by default ?

### ISSUE THREAD

**Issue by jlecour** [unwire/handsoap#13]
Hi,

I've read that curb is the default http driver, but in "lib/handsoap/parser.rb" I see an explicit require for "httpclient".

Is it a mistake or I'm missing something ?

Thanks

**Comment by troelskn** [comment]
`Handsoap::Parser` is not part of the runtime for Handsoap - It's only used by the generator. I guess it could use the http-abstraction layer just like the rest of the library, but I figured it didn't matter much for the generator. Call me lazy.

**Comment by jlecour** [comment]
Thank you for this quick answer.
I won't call you lazy ;-) I just wish It'd have been written somewhere, for example a comment just above the "require", but that said, it's not a problem, I installed 'httpclient' and it worked as expected.

Thanks again.

**Comment by troelskn** [comment]
I'll pop a comment in there. The nice thing about `httpclient` is that it's all ruby code, so it works the same across different platforms. It's slow as molasses though, so it's not a good pick for runtime.
