### ISSUE TITLE
Does not parse namespaces containing quotes

### ISSUE THREAD

**Issue by vadimt** [unwire/handsoap#14]
The following response throws a 'The response is not a valid SOAP envelope' error due to the single quotes in xmlns:ns1="'daily'_type_quota"

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="'daily'_type_quota" xmlns:ns2="urn:EntityService" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">SOAP-ENV:Headerns1:remaining_quota23992/ns1:remaining_quotans1:quota_used_so_far8/ns1:quota_used_so_farns1:command_groupAccountManagement/ns1:command_groupns1:quota_typedaily/ns1:quota_type/SOAP-ENV:HeaderSOAP-ENV:Bodyns2:addResponse<entity_id xsi:type="xsd:long">335511</entity_id>/ns2:addResponse/SOAP-ENV:Body/SOAP-ENV:Envelope

**Comment by troelskn** [comment]
I'm curious - What's the use case or this? Do you actually have an application with a namespace that contains quotes?

I'll look into the issue, but likely the problem happens at the xml-parser level. Off the top of my head, I'm actually unsure if the above is valid xml.

**Comment by vadimt** [comment]
This is actually xml that is coming back from an external application API I am integrating with.  I wasn't sure if it was valid either, but http://www.w3schools.com/Xml/xml_attributes.asp says that it's ok.

**Comment by zentourist** [comment]
I cannot replicate this issue in any of the XML parsers.  What ruby version and XML parser are you using?  I tested both Ruby 1.8.7 and 1.9.2 using this spec file:

http://gist.github.com/559345

**Comment by vadimt** [comment]
Thanks for looking into this

Ruby 1.8.7 patchlevel 174
Nokogiri 1.4.3.1
Handsoap 1.1.7

The error occurred when running tests using VCR with webmock, changing the mock to remove the single quotes did not throw the error.

**Comment by zentourist** [comment]
I replicated the error somewhat and traced it back to libxml2.  You can try using xmllint which comes with libxml2 to see it throw an error on the namespace with quotes.  I tried parsing it with REXML and that worked a bit better.  Try and set
    Handsoap.xml_query_driver = :rexml
and see if that works better for you.

**Comment by vadimt** [comment]
Right on, thank you.
