### ISSUE TITLE
Rails 3 generator

### ISSUE THREAD

**Issue by matthewford** [unwire/handsoap#16]
Could we get a rails 3 version of the generator?

**Comment by bobcalco** [comment]
I would second this request. Either that or give me a way to use the generator outside of Rails.

**Comment by DavidEGrayson** [comment]
I second this request.  Also, it seems like you have to install Rails 2 just to run the tests for this gem, so that is not cool.

**Comment by troelskn** [comment]
I'm not doing much Ruby these days, so I'm not using this library currently. As such, don't hold your breath for me to implement a Rails 3 generator. That said, the generator is rather simple - Most of the heavy lifting happens in the library code (Specifically in `handsoap/parser.rb`). So if you're up to it, a pull request would be appreciated.
