### ISSUE TITLE
REXML query driver problem with text nodes

### ISSUE THREAD

**Issue by gettalong** [unwire/handsoap#2]
Hi,

when using REXML as query driver there is a problem when using `#to_s` on an element returned by an XPath with `text()` like `./ns:Element/text()` since the returned REXML element is of type REXML::Text which does not have a `#text` method. However, the text value can be returned by using the `#value` method. So an additional check for the REXML::Text element is needed.

Best regards,
  Thomas

**Comment by troelskn** [comment]
Fixed in http://github.com/unwire/handsoap/commit/56c5a101872b886b38a954e4c8d3f1cf34dc9874
