### ISSUE TITLE
No gem generated

### ISSUE THREAD

**Issue by gettalong** [unwire/handsoap#3]
Hi,

although the last change of the gemspec is many hours ago, no 1.0.0 gem has been built.

Best regards,
  Thomas

**Comment by rud** [comment]
Just found the "track build progress" page: http://hasmygembuiltyet.org/unwire/handsoap

**Comment by jimmiw** [comment]
It seems that github no longer supports building gem.
This was pointed out here: http://github.com/unwire/handsoap/issues#issue/5 (this issue also has a deep link to the actual github blog post)

We'll try to keep both issues up-to-date, and will try to get the new gem up asap

**Comment by troelskn** [comment]
Gem is now at: http://gemcutter.org/gems/handsoap

**Comment by rud** [comment]
Works - just successfully installed handsoap-1.1.0 gem from gemcutter :)
