### ISSUE TITLE
Push handsoap gem to gemcutter

### ISSUE THREAD

**Issue by erikdahlstrand** [unwire/handsoap#5]
Gem Building is Defunct. Please see http://github.com/blog/515-gem-building-is-defunct
Please push to gemcutter (http://gemcutter.org/) instead.

**Comment by jimmiw** [comment]
thanks for the heads up. We are currently looking into the issue

**Comment by troelskn** [comment]
Gem is now at: http://gemcutter.org/gems/handsoap
