### ISSUE TITLE
Add curb as gem dependency

### ISSUE THREAD

**Issue by pacoguzman** [unwire/handsoap#9]
Hi,

I'm trying to use handsoap in a clean ruby 1.8.7 installation and when I install handsoap I can't run it without curb gem installed.

Maybe could be posible to add curb as a gem dependecy

Thanks

**Comment by troelskn** [comment]
Thing is, Handsoap works with several drivers - not just curb. Adding curb as a dependency would make it impossible to install Handsoap without curb, which is a valid thing to do.
